### ISSUE TITLE
collection update not working

### ISSUE THREAD

**Issue by zenmatt** [percolatestudio/meteor-migrations#11]
Baffled by this code not working. I've tested it from the mongo console which works, I've console logged to ensure I am in the up/down functions, but the update has no effect.

`````` Migrations.add({
  version: 2,
  name: 'Add blah to Collection',
  up: function () {
    Collection.update({}, {$set:{blah:""}}, {multi:true});
  },
  down: function () {
    Collection.update({}, {$unset: {blah:1}}, {multi:true});
  }
});```
``````

**Comment by MattG561** [comment]
I am also facing this issue. Would be nice if the fix was posted within the thread.
