### ISSUE TITLE
Migrating back to Version 0 does not work

### ISSUE THREAD

**Issue by mccormjt** [percolatestudio/meteor-migrations#17]
Everything seems to work fine for migrating to and from versions above 0. However when trying to migrate back down to 0 nothing seems to happen. 
Using command:

Migrations.migrateTo(0);

It just stays on the current version it was already at and I do not get any errors.

Thanks for your help

**Comment by zol** [comment]
Thanks for reporting this @mccormjt, I've confirmed the issue.

**Comment by zol** [comment]
Fixed and release version 0.7.3

**Comment by mccormjt** [comment]
np, thanks! :D
