### ISSUE TITLE
Get Current Version

### ISSUE THREAD

**Issue by mccormjt** [percolatestudio/meteor-migrations#18]
This is fairly simple, but it would be nice to see which version you are on. Could be useful if you are tinkering around. Something like -> Migrations.currentVersion()

**Comment by zol** [comment]
@mccormjt This already exists. Call `Migrations.getVersion`. I will document it now.

**Comment by mccormjt** [comment]
great thanks!

**Comment by sungwoncho** [comment]
How about storing the history of the migration in the db? Rails does this and I think it's quite useful.

That way, I don't have to try to run `Migrations.getVersion` on the server side every time I need to check the current migration version.
