### ISSUE TITLE
Version bump?

### ISSUE THREAD

**Issue by iameli** [percolatestudio/meteor-migrations#24]
https://github.com/percolatestudio/meteor-migrations/pull/22 is necessary for this package to work within another package. Otherwise I just get `ReferenceError: check is not defined` when it tries to start up. Can we get a bump to 0.7.4 so this can be easily included in a package?

**Comment by zol** [comment]
Done. Sorry about the delay.

**Comment by iameli** [comment]
No worries, thank you.
