### ISSUE TITLE
Recommended way to use?

### ISSUE THREAD

**Issue by wizonesolutions** [percolatestudio/meteor-migrations#32]
I like how this package at least lets me not have migrations run until I've written the code for them. But is there a decent way to script migrations and have them get run by a deploy script? If you've done anything like this with the package, it'd be neat to have some examples in the README.

**Comment by zol** [comment]
I used to provide a shell script that would hackily use env variables to allow you to run migrations from the command line. At some point around Meteor version 0.9 this approach started to break and I never had the time to investigate. I believe @stubailo may look at this problem sometime soon.
