### ISSUE TITLE
Package specific data versions

### ISSUE THREAD

**Issue by tedgoldstein** [percolatestudio/meteor-migrations#41]
Is there a way to use the Migration package to support multiple package-specific data versions?

For example, package-A introduces its own collections, which is versioned.  package-B has its own  collections. The app as a whole has its collections. Therefore there are three separate independent  version series.

Perhaps this is a feature request.
Thanks
Ted

**Comment by zol** [comment]
Hey Ted, No there isn't a feature to do this. I'm afraid it's also probably out of the scope of this package.
