### ISSUE TITLE
Feature Request: custom name for migration collection

### ISSUE THREAD

**Issue by achtan** [percolatestudio/meteor-migrations#48]
In Dr. Mongo we are prefixing all our collection with `drmongo.` string https://github.com/DrMongo/DrMongo/blob/master/lib/constants.js#L3

is it passible to customizing name of migration collection?

**Comment by zol** [comment]
It's currently not possible to configure the name of the collection.

**Comment by achtan** [comment]
are you planing to implement this feature ?

**Comment by zol** [comment]
I'm not in the foreseeable future.

**Comment by willatpractichem** [comment]
I created a pull request to implement this feature in #52

**Comment by achtan** [comment]
@willatpractichem you are the man!
