### ISSUE TITLE
Detect failed migration in Meteor UI

### ISSUE THREAD

**Issue by damienrobson** [percolatestudio/meteor-migrations#58]
Is there a "best practice" way of detecting a failed migration from within Meteor? My use case is that my app is hosted on Modulus.io, so if a migration fails I have no way of knowing unless I check the logs there. 

Basically, if a migration fails I want a way to flag this to our admin team from the UI so that they can do something about it.

**Comment by hexsprite** [comment]
a good idea is to make a clone of your production DB and run a test migration against that. as for best practice, just read the logs whenever you deploy a migration. Or if you use something like papertrail you could setup an alert for a failed migration string and it will slack/email/sms you whenever that occurs.
