### ISSUE TITLE
Where to put migration startup code in Meteor 1.3+

### ISSUE THREAD

**Issue by BradRyan** [percolatestudio/meteor-migrations#60]
I'm trying to upgrade my app to 1.3.2.4 and move all my server code into my `/imports` folder, but I'm running into trouble with this package.  When I include `Migrations.migrateTo('latest');` inside of `/imports/server/startup`, I get the error "Cannot call method 'findOne' of undefined".  

I've tried with and without `import { Migrations } from 'meteor/percolate:migrations';` at the top of the file. It doesn't look like Migrations is an exported variable in the package, so I would assume this would remain available as a global.  Perhaps this folder loads before the package Global is available?

Confused 😕

**Comment by tentakel** [comment]
i've been having the exact same problem. haven't figured out a solution for it yet

**Comment by npu3paka** [comment]
Do you use other packages or this is on new project as well?

**Comment by tentakel** [comment]
@npu3paka the relevant packages for this might be collection2 and simple-schema. apart from that, no other packages that directly influence migrations

**Comment by npu3paka** [comment]
Thank you. I will check it on few versions and upload fix asap.

**Comment by abhiaiyer91** [comment]
I'm having the same issue. `'TypeError: Cannot call method \'findOne\' of undefined`

**Comment by tmeasday** [comment]
I think this is just a matter of ensuring you call `Migrations.x` within a `Meteor.startup` block.

**Comment by abhiaiyer91** [comment]
Yes but that can't be the solution for people depending on things by package load order right? If we're expecting certain deps today how can we start cluttering meteor startup calls everywhwre

**Comment by tmeasday** [comment]
I'm not sure what you guys were doing before, but `Migrations._collection` is created in a startup block: https://github.com/percolatestudio/meteor-migrations/blob/master/migrations_server.js#L93, so package load order aside, you can't call into `Migrations` until after startup. 

I'm not sure if this changed at some point and you got a new version of `migrations` included in the update to 1.3, but this issue isn't caused by anything Meteor-wise that changed in 1.3, AFAICT.

**Comment by BradRyan** [comment]
Before, I had `Migrations.migrateTo('latest');` located inside a `Meteor.startup` block in the path `/server/migrations/index.js`.  When I place the same code without the Meteor.startup block in the path `/imports/server/startup`, I get the errors described above.

When I move the code back into the server folder wrapped in a startup block (which is where it is now) things work again with the latest migrations package.  @tmeasday are you saying that you can't reproduce it then?  I can try this in a boilerplate and see if I can reproduce it if that's what we are looking for.

**Comment by tmeasday** [comment]
I think you're right, I'll fix that.
