### ISSUE TITLE
Locking is done too early

### ISSUE THREAD

**Issue by Ehrs** [percolatestudio/meteor-migrations#80]
We got a hanging lock in production due to too early locking in `_migrateTo`. It was an unfortunate timing of a second restart but I think it could be avoided if locking is done later.

The lock was taken by a meteor instance and that instance got almost immediately restarted, before it had unlocked. If instead `_migrateTo` checked if it needed to do any migration first and _then_ locked we would never have gotten a hanging lock since our database was already latest.

A fix for this would revert some changes in #38 by @meonkeys but only to re-introduce more fine-grained locking.

Thoughts?

**Comment by Ehrs** [comment]
Pull request #81 fixes this.

**Comment by StorytellerCZ** [comment]
Released in 1.0.3
