### ISSUE TITLE
Migrate to async (Meteor 2.8 and onwards)

### ISSUE THREAD

**Issue by perbergland** [percolatestudio/meteor-migrations#84]
This package will need to be updated for fibers-free meteor:

* Use *Async mongodb methods and adapt code to be async and that migration functions need to be awaited since they can also be async

**Comment by StorytellerCZ** [comment]
Started working on this.

**Comment by bratelefant** [comment]
What's the current state on this? I got a local clone with asynchronous support added. Could get a fork up

**Comment by lc3t35** [comment]
Will it be merged to master ? or do we need to get the package of release-2.0 branch locally ?
how can we add it to meteor as version 2 ?
Thank you
